[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions/"